### ISSUE TITLE
图片浏览顺序不对

### ISSUE THREAD

**Issue by hen0920** [bluebabes/tuliu#1]
列表顺序是对的，但是单击进入浏览后浏览的顺序就不对了，变成按照列表里瀑布流的纵向排列的顺序了

测试网址：https://www.bilibili.com/read/cv20371043
![微信截图_20230318230539](https://user-images.githubusercontent.com/35443965/226114195-fef5f4d2-1683-4800-ab4b-902d736d685a.jpg)
![微信截图_20230318230603](https://user-images.githubusercontent.com/35443965/226114199-592b9ef9-409a-49d3-99c4-c62a1fe6e3ac.jpg)

另外有时候单击列表项会变成打开新标签页而不是进入图片浏览

**Comment by bluebabes** [comment]
确实有这个问题

**Comment by bluebabes** [comment]
<img width="1909" alt="image" src="https://github.com/bluebabes/tuliu/assets/3329261/fab80bd7-4991-4c38-bf41-8337277f0aa0">
<img width="1918" alt="image" src="https://github.com/bluebabes/tuliu/assets/3329261/1523e36d-c5a5-42bd-a6dd-35a90a4c8262">

增加漫画模式， 幻灯片在漫画模式下打开


版本： v1.5.30

**Comment by bluebabes** [comment]
@hen0920
