### ISSUE TITLE
请问可以申请图流的会员吗

### ISSUE THREAD

**Issue by wangyuan9527** [bluebabes/tuliu#3]
很喜欢用这个插件，一直在用不知道会员会解锁什么。期待满满

**Comment by bluebabes** [comment]
报id给你体验下。。。

**Comment by wangyuan9527** [comment]
非常感谢您！我的id：wangyuan9527 密码：15039947371w&nbsp; 希望咱们的图流可以也越来越好！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bluebabes/tuliu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月20日(星期一) 下午2:42
***@***.***&gt;;
抄送:&nbsp;"独特ゝ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [bluebabes/tuliu] 请问可以申请图流的会员吗 (Issue #3)





 
报id给你体验下。。。

**Comment by bluebabes** [comment]
xxxx 密码也发啊。。。 加了一个月
